name: Run pnpm install
description: Run a pnpm install with optional command
inputs:
  command:
    description: The command to run
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: package.json
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm install
      shell: bash
    - run: cp .env.example .env.local
      shell: bash
    - run: ${{ inputs.command }}
      shell: bash
