name: Run check
description: Run a CI check
inputs:
  command:
    description: The command to run
    # required: false
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: package.json
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml
    - run: pnpm install
      shell: bash
    - run: cp .env.example .env.local
      shell: bash
    - run: ${{ inputs.command }}
      shell: bash
