name: E2E tests
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
# concurrency:
#   group: ${{ github.ref }}
#   cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 60
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/run-check
        with:
          command: echo "blah"

      # Uses container with browser dependencies pre-installed as this is faster
      # Slower version with cache has been removed here:
      # https://github.com/IgorKrupenja/nextjs-starter/commit/4b6a52fa33341cbd87f63d0c79366ce679a1b2b8
      - name: Run E2E tests
        uses: docker://mcr.microsoft.com/playwright:v1.44.1-jammy
        with:
          # The container does not have pnpm
          # env HOME=/root is needed for Firefox
          args: bash -c "npm install -g pnpm && env HOME=/root pnpm run test:e2e"

      - name: Store Artifacts from Failed Tests
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-results/
          retention-days: 7
