name: Run check
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
jobs:
  run-check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-check
        with:
          command: ${{ inputs.command }}
