name: Run CI checks
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
jobs:
  format:
    uses: ./.github/workflows/run-check.yml
    with:
      command: pnpm run format:check
  lint:
    uses: ./.github/workflows/run-check.yml
    with:
      command: pnpm run lint:check
  test:
    uses: ./.github/workflows/run-check.yml
    with:
      command: pnpm test
  build:
    uses: ./.github/workflows/run-check.yml
    with:
      command: pnpm run build
